name: nginx-deployment
on: push
jobs:
 my-job:
   runs-on: Windows
   steps: 
     - name: Checkout
       uses: actions/checkout@v3
     - name: Build Images
       shell: pwsh
       run: docker build -t karrisudhakar/public-git-repo .
     - name: Push Image
       shell: pwsh
       run: docker push karrisudhakar/public-git-repo
